name: Prettier Test

on:
  push:
    branches: [main]
    paths:
    - '**.js'
  pull_request:
    branches:
    - main
    paths:
    - '**.js'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Prettify code
      uses: creyD/prettier_action@dev
      with:
        prettier_options: --write **/*.js